name: Auto Update Heatmap Data

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install shapely
        run: pip install shapely

      - name: Generate New Heatmap Data
        run: python update_heatmap.py

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
