name: Auto Update Heatmap Data

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate New Heatmap Data
      run: |
        python update_heatmap.py

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add heatmap-data.json
        git commit -m "🔄 auto: update dense heatmap"
        git push
